// ROUTING EXAMPLE..

const express = require('express');
const app = express();


// JAB DATA CLIENT SY AYE GA TU WO REQUES WALY PARAMETER MEIN AYE GA.

// OR AGAR KOII SERVER RESPOND KAREGA TU RESPONSE PARAMETER MEIN AYE GA.


